#include <torch/csrc/jit/ir/ir.h>

namespace fastseq {
namespace jit {

/** \brief Match the at::linear pattern and fuse it into a single at::linear
 * This pass fuse the addmm or matmul + add generated by JIT back to linear
 * This pass can be deleted once the JIT can emit the aten::linear in the future
 */
using namespace torch::jit;

void FuseLayerNorm(std::shared_ptr< torch::jit::Graph>& graph);
} // namespace jit
} // namespace torch
